// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCIdFwZBtjI_D4STc8Oo-tEbZuhuDOTw',
    appId: '1:385891849550:web:64a5567fd50241bb603a1f',
    messagingSenderId: '385891849550',
    projectId: 'fitnessappflutter-57e48',
    authDomain: 'fitnessappflutter-57e48.firebaseapp.com',
    storageBucket: 'fitnessappflutter-57e48.firebasestorage.app',
    measurementId: 'G-BG6YP65SW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCob5qPj986kA8FdZV9mWC3v7x1nh9w6AA',
    appId: '1:385891849550:android:86b9bd36c5f9a4ea603a1f',
    messagingSenderId: '385891849550',
    projectId: 'fitnessappflutter-57e48',
    storageBucket: 'fitnessappflutter-57e48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWymL8fkn80ulkof9nAEOzARcZwae3Vw',
    appId: '1:385891849550:ios:a96b0d31cd8117ec603a1f',
    messagingSenderId: '385891849550',
    projectId: 'fitnessappflutter-57e48',
    storageBucket: 'fitnessappflutter-57e48.firebasestorage.app',
    iosClientId: '385891849550-9vfimu2um81i8a6rc4a1oqthil3in0q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABWymL8fkn80ulkof9nAEOzARcZwae3Vw',
    appId: '1:385891849550:ios:a96b0d31cd8117ec603a1f',
    messagingSenderId: '385891849550',
    projectId: 'fitnessappflutter-57e48',
    storageBucket: 'fitnessappflutter-57e48.firebasestorage.app',
    iosClientId: '385891849550-9vfimu2um81i8a6rc4a1oqthil3in0q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxCIdFwZBtjI_D4STc8Oo-tEbZuhuDOTw',
    appId: '1:385891849550:web:a01fafa5f6556142603a1f',
    messagingSenderId: '385891849550',
    projectId: 'fitnessappflutter-57e48',
    authDomain: 'fitnessappflutter-57e48.firebaseapp.com',
    storageBucket: 'fitnessappflutter-57e48.firebasestorage.app',
    measurementId: 'G-9YH5CYC67K',
  );

}